### PR TITLE
Support 7bit, 8bit, binary transfer-encodings

### PR DESCRIPTION
**Pull request by thosakwe**
While sending `http.MultipartRequest` with both files and fields to a Dart server, I kept getting `Unsupported contentTransferEncoding: binary` errors. I realized that `http_server` doesn't support any values of `transfer-encoding` for multipart parts.

According to [RFC1341](https://www.w3.org/Protocols/rfc1341/5_Content-Transfer-Encoding.html), the `7bit`, `8bit`, and `binary` transfer encodings are effectively transparent, and indicate no specific encoding of content.

This PR just checks if the given transfer encoding is either null, or one of `7bit`, `8bit`, or `binary`.

### CODE REVIEW

**Review by natebosch — APPROVED** [review]

**Comment by kevmoo** [comment]
@natebosch – tests failing? changelog? merging? 😄

**Comment by natebosch** [comment]
> tests failing? changelog? merging? 😄

Done.

**Comment by natebosch** [comment]
@jakemac53 - can you add a second pair of eyes on this review?

**Review by jakemac53 — APPROVED** [review]

**Comment by thosakwe** [comment]
Thanks everyone!

**Pull request merged**
